//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduledTask {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class nlog : global::System.Configuration.ApplicationSettingsBase {
        
        private static nlog defaultInstance = ((nlog)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new nlog())));
        
        public static nlog Default {
            get {
                return defaultInstance;
            }
        }
    }
}
